MA-19109-1 [#imx-2582] fix nn-imx 1.3.0 compile error in android 12
Meet the below compile error:
vendor/nxp-opensource/nn-imx/nn_runtime/android_hal/VsiPlatform.h:179:8: error: redefinition of 'Hal<31>'
struct Hal<31> {
       ^~~~~~~
vendor/nxp-opensource/nn-imx/nn_runtime/android_hal/VsiPlatform.h:143:8: note: previous definition is here
struct Hal<ANDROID_SDK_VERSION> {
       ^
1 error generated.

The below commit add Hal<31>:
+#if ANDROID_SDK_VERSION >= 31
+template <>
+struct Hal<31> {

0d67d0de Support Android S build for nxp

Here revert the below patch:
0792090f MA-19109 [#imx-2582] Fix nn-imx compile error in android 12

This reverts commit 0792090f4abdfb10b1d8c3c37f9c88cbee6c2c94.

Signed-off-by: Jessie Hao <juan.hao@nxp.com>