makefile: Ignore clean failures
The clean operation can cause a build failure when there is nothing to
be removed. This failure can cause Yocto build to fail for no good
reason:

```
ERROR: nn-imx-1.2.0-r0 do_configure: Execution of '/opt2/hardknott/build/tmp/work/cortexa72-cortexa53-crypto-poky-linux/nn-imx/1.2.0-r0/temp/run.do_configure.19981' failed with exit code 1:
remove *.so and *.o
rm: cannot remove '*.o': No such file or directory
makefile:20: recipe for target 'clean' failed
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>